### ISSUE TITLE
Panic: Malformed Version

### ISSUE THREAD

**Issue by jrstarke** [paultyng/go-unifi#26]
I'm still relatively new to Go, so apologies if I'm completely off base.

I haven't run a terraform plan since before my UDM got upgraded to 6.0, so there are likely many things that changed in this time.

**Versions**

* Terraform: v0.13.0
* paultyng/unifi: v0.20.0
* Unifi Controller: 6.0.43
* Unifi Controller Build: atag_6.0.43_14348
* UDM Firmware: 1.8.6.2969

What I'm seeing is in the terraform trace appears to be:

1. It logs in with a `POST` to the `/api/auth/login` endpoint
2. This responds back with `200 OK` as well as a json response for the details for my account
3. Performs a `GET` to `/proxy/network/status`
4. Receives `200 OK` response with json 
```
{
 "meta": {
  "rc": "ok",
  "uuid": "<redacted>"
 },
 "data": []
}
```
Followed by
```
2021-02-24T22:28:45.611-0800 [INFO]  plugin.terraform-provider-unifi_v0.20.0: 2021/02/24 22:28:45 [TRACE] Unifi controller version: "": timestamp=2021-02-24T22:28:45.610-0800
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0:
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
panic: Malformed version:
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0:
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: goroutine 56 [running]:
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/go-version.Must(...)
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/go-version@v1.2.1/version.go:104
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/paultyng/terraform-provider-unifi/internal/provider.(*client).ControllerVersion(0xc000360000, 0x0)
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/paultyng/terraform-provider-unifi/internal/provider/provider.go:197 +0x95
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/paultyng/terraform-provider-unifi/internal/provider.dataAPGroupRead(0xc00028ee00, 0x17ee1a0, 0xc000360000, 0x1e6d730, 0x192a9c0)
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/paultyng/terraform-provider-unifi/internal/provider/data_ap_group.go:40 +0x5b
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000122780, 0x19e9b00, 0xc0002feb00, 0xc00028ee00, 0x17ee1a0, 0xc000360000, 0x0, 0x0, 0x0)
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:290 +0x88
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000122780, 0x19e9b00, 0xc0002feb00, 0xc00047ec00, 0x17ee1a0, 0xc000360000, 0xc000360000, 0xc00047ec00, 0x0, 0x0)
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:498 +0xfd
2021-02-24T22:28:45.613-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003c1200, 0x19e9b00, 0xc0002feb00, 0xc00047eb20, 0xc0002feb00, 0x1879cc0, 0x18a87a0)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:1105 +0x4d4
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc0003c0700, 0x19e9b00, 0xc0002feb00, 0xc000476870, 0xc0003c0700, 0xc000486ba0, 0x106a5e7)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:247 +0xe5
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x18a87a0, 0xc0003c0700, 0x19e9bc0, 0xc00058a600, 0xc0000b3da0, 0x0, 0x19e9bc0, 0xc00058a600, 0xc0000b7020, 0x2a)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00019c8c0, 0x19f1c80, 0xc0002a2180, 0xc0001c2800, 0xc000202570, 0x1e2f8f0, 0x0, 0x0, 0x0)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	google.golang.org/grpc@v1.35.0/server.go:1217 +0x522
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: google.golang.org/grpc.(*Server).handleStream(0xc00019c8c0, 0x19f1c80, 0xc0002a2180, 0xc0001c2800, 0x0)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	google.golang.org/grpc@v1.35.0/server.go:1540 +0xd05
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000036210, 0xc00019c8c0, 0x19f1c80, 0xc0002a2180, 0xc0001c2800)
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	google.golang.org/grpc@v1.35.0/server.go:878 +0xa5
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-24T22:28:45.614-0800 [DEBUG] plugin.terraform-provider-unifi_v0.20.0: 	google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
2021-02-24T22:28:45.616-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/paultyng/unifi/0.20.0/darwin_amd64/terraform-provider-unifi_v0.20.0 pid=77081 error="exit status 2"
2021-02-24T22:28:45.616-0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/02/24 22:28:45 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/02/24 22:28:45 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/02/24 22:28:45 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
```

Looking at [the struct that I'm assuming is used to define the schema of the json response](https://github.com/paultyng/go-unifi/blob/main/unifi/unifi.go#L143-L148), it appears that it's expecting a `server_version` property in the `meta` object, but no such thing appears to be in the response I'm getting.

From the above it does seem to confirm that the version is empty on the line following the json response.

When we try to compare this version to [`controllerV6` in `dataAPGroupRead`](https://github.com/paultyng/terraform-provider-unifi/blob/main/internal/provider/data_ap_group.go#L40) it appears to panic

**Comment by paultyng** [comment]
This is a UDM or a UDM Pro? 

The provider is tested against 6.0.45 of the controller right now at least, but I can probably test on 6.0.43 to see if anything different. I only have a UDM, not a UDM-Pro, so hard to simulate the differences in the API interactions between the two until I can get one of each setup for testing.

**Comment by jrstarke** [comment]
I just have a UDM. I did come across [a question on the UniFi forums](https://community.ui.com/questions/Status-API-changed-on-UDMP-or-Network-Controller/69d75ad8-5d03-4044-ab67-e7c017bb784c?page=0) related to this, but the author was using a UDM pro, and someone verified that on 6.0.43 the property should show up, which is why I included the udm firmware version, as the author reported the issue in 1.8.5, so I thought maybe it was something turned off in the firmware, or a toggle somewhere

**Comment by paultyng** [comment]
Got it, let me test on my UDM, it looks like its upgraded as well and I haven't re-run my config against it since then.

**Comment by paultyng** [comment]
Still on my list, sorry for the delay here. Recently left my job so don't have a development machine ready to go and machines/parts are severely backordered. Trying to make due with a very old laptop but its painful and had to set everything back up.

I am able to repro this locally, still poking at it though.

**Comment by paultyng** [comment]
I think this is now addressed in v0.22.0 of the provider, its working for me locally at least. Let me know if it works for you.

**Comment by jrstarke** [comment]
Thanks for looking into this. I confirmed that I still get the crash in v0.20.0, then verified that it goes away both v0.22.0 and v0.23.0. Thanks for your help :)
